### ISSUE TITLE
An error occurred communicating with Zotero:

### ISSUE THREAD

**Issue by StarPicard** [zotero/zotero-libreoffice-integration#37]
Hello I have a big problem. Everytime I try to add citations to LibreOffice I get the error message above.
Nothing really changed on my system...

Hope someone can help me fast, I have to write an abstract for university ;)

Here the detail information:
```
An error occurred communicating with Zotero:
java.lang.NullPointerException
    at org.zotero.integration.ooo.comp.TextTableManager.<init>(TextTableManager.java:64)
    at org.zotero.integration.ooo.comp.ReferenceMark.getDocumentRange(ReferenceMark.java:347)
    at org.zotero.integration.ooo.comp.ReferenceMark.compareTo(ReferenceMark.java:357)
    at org.zotero.integration.ooo.comp.ReferenceMark.compareTo(ReferenceMark.java:1)
    at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
    at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
    at java.util.Arrays.sort(Arrays.java:1312)
    at java.util.Arrays.sort(Arrays.java:1506)
    at java.util.ArrayList.sort(ArrayList.java:1462)
    at java.util.Collections.sort(Collections.java:141)
    at org.zotero.integration.ooo.comp.Document.getFields(Document.java:404)
    at org.zotero.integration.ooo.comp.CommMessage.execute(CommMessage.java:107)
    at org.zotero.integration.ooo.comp.CommMessage.getBytes(CommMessage.java:61)
    at org.zotero.integration.ooo.comp.CommServer.run(CommServer.java:84)
    at java.lang.Thread.run(Thread.java:748)
```
And from console:
```
Possibly unhandled rejection:

err is null

TypeError: err is null
    logError@chrome://zotero/content/xpcom/zotero.js:1300:3
    execCommand@chrome://zotero/content/xpcom/integration.js:276:7
From previous event:
    Comm</DataListener.prototype._transactionCallbacks[0]<@file:///usr/lib/zotero/extensions/zoteroOpenOfficeIntegration@zotero.org/components/zoteroOpenOfficeIntegration.js:168:6
    Comm</DataListener.prototype._processFrame/<@file:///usr/lib/zotero/extensions/zoteroOpenOfficeIntegration@zotero.org/components/zoteroOpenOfficeIntegration.js:273:7
    this.setTimeout/timerCallback.notify@chrome://zotero/content/xpcom/zotero.js:1780:5
Possibly unhandled rejection:
```

**Comment by adomasven** [comment]
Please post support requests on [Zotero forums](forums.zotero.org). The tracker is for developer use only.
